### ISSUE TITLE
Unneseccary await signal in Globals

### ISSUE THREAD

**Issue by Karolinskis** [Nekompiliuoja/Champions-of-the-Realm#90]
**Describe the bug**
`Globals.cs` / `LoadGame` method. When game loads (from save file) it must free every scene in scene tree (in group of Persist nodes) it takes time and currently timer is creating with short amount of waiting time to free all the scenes before adding new ones. This type of work around is unreliable and must be changed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 11]

**Additional context**

**Comment by Elijuszek** [comment]
Solved in #80 PR
